use_frameworks!

platform :ios, '9.0'

target 'BinanceSmartChainSDK_Example' do
  pod 'BinanceSmartChainSDK', :path => '../'
  pod 'web3swift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  
  target 'BinanceSmartChainSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
